services:
    fixturama.faker.generator:
        class: Faker\Generator
        factory: ['Faker\Factory', 'create']

    fixturama.yaml.parser:
        class: Symfony\Component\Yaml\Parser

    fixturama.pdo:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\FixturamaPDO
        arguments: ["@=service('naldz.dsnparser.parser').parse(parameter('fixturama.dsn'))"]

    fixturama.generator:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\FixtureGenerator
        arguments: [@fixturama.schema_definition, @fixturama.model_fixture_generator]

    fixturama.model_fixture_generator:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\ModelFixtureGenerator
        arguments: [@fixturama.faker.generator]

    fixturama.schema_definition:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\Schema\SchemaDefinition
        arguments: [%fixturama.model_definition%]

    fixturama.sql_converter:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\SqlConverter
        arguments: [@fixturama.schema_definition, @fixturama.pdo]

    fixturama.loader:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\FixtureLoader
        arguments: [@fixturama.schema_definition, @fixturama.sql_converter, @fixturama.pdo]

    fixturama.manager:
        class: Naldz\Bundle\FixturamaBundle\Fixturama\Fixturama
        arguments: [@fixturama.generator, @fixturama.loader]